name: Deploy Python Application on AWS

on:
  push:
    branches:
      - QA
      - master
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t dssanguano/frontend-final:${{ github.ref_name }} .

      - name: Push Docker Image
        run: docker push dssanguano/frontend-finals:${{ github.ref_name }}

  deploy-qa:
    if: github.ref_name == ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for Dev
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/qa_key.pem
          chmod 600 /home/runner/.ssh/qa_key.pem

      - name: Deploy to QA Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/qa_key.pem ubuntu@${{ secrets.HOST}} << 'EOF'
          if ! command -v docker &> /dev/null; then
            echo "Docker no está instalado. Procediendo a instalar..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ubuntu
            echo "Docker instalado exitosamente."
          else
            echo "Docker ya está instalado."
          fi
          sudo docker pull dssanguano/frontend-final:${{ github.ref_name }}
          sudo docker rm -f frontend-final-container || true
          sudo docker run -d -p 5000:5000 --name frontend-final-container dssanguano/frontend-final:${{ github.ref_name }}
          EOF

